---
title: "Exploratory analysis using group_by"
author: "Olya Besedina"
data: "10/03/2019"
output: github_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(viridis)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8
  fig.height = 6,
  out.width = "90%"
)

# copy the rest from github


```

# create data frame

```{r load data, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

# group_by
```{r}
view(weather_df)
weather_df %>%
  group_by(name, month)
```


```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n())
```


# summirize by unique obs., n_distinct

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(n_obs = n(),
            n_unique = n_distinct(date))
```

# count

```{r}
weather_df %>% 
  count(name)

```

# can rename
```{r}
weather_df %>%
  count(month, name = "n_days")
```

# dont use this. terrible

```{r, eval = FALSE}
weather_df %>% 
  pull(name) %>% 
  table()
```

