---
  title: "Vizualizatipn and EDA Part 2"
author: "Olya Besedina"
data: "10/01/2019"
output: github_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(patchwork)
```

```{r load data, cache=TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

# making new plots
Add labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha = .5) +
  labs (
    title = "Temperature plot",
    x = "Min temp",
    y = "Max temp",
    caption = "Data from NOAA via rnoaa pachage"
  )
```

x axis adn y axis 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") + 
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15ยบ C", "0", "15"))+
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```


## colors and other plot details
```{r}
ggp_base = weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature (C)",
    y = "Maxiumum daily temperature (C)",
    caption = "Data from the rnoaa package") +
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )
```

## Themes
```{r}
ggp_base +
  theme_bw() +
  theme(legend.position = "bottom")
```

Minimal theme must be on the top before other themes 

```{r}
ggp_base +
  theme_minimal() +
  theme(legend.position = "bottom")
```

(Where do my warnings come from?)
```{r}
weather_df %>% 
  filter(is.na(tmin))
```

## more than one data set
```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name))+
  geom_point() +
  geom_line(data = central_park)
```


(Brief aside about colors)
```{r}
waikiki %>% 
  ggplot(aes(x = date, y = tmax)) +
  geom_point(alpha = .5, color = "blue")
  
```


## Multi-panel plots

```{r}
# devtools::install_github("thomasp85/patchwork")
ggp_scatter = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

ggp_density =
  weather_df %>% 
  ggplot(aes(x = tmin))+ 
  geom_density()

ggp_box = 
  weather_df %>% 
  ggplot(aes(x = name, y = tmax, color = name))+
  geom_boxplot()

ggp_scatter + (ggp_density + ggp_box)
```


## Data manipulation

Change order

```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = fct_relevel(name, "Waikiki_HA", "CentralPark_NY")
  ) %>% 
  ggplot(aes(x = name, y = tmax, color = name))+
  geom_boxplot()
```


reorder in sntead of relevel

```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = fct_reorder(name, tmax)
  ) %>% 
  ggplot(aes(x = name, y = tmax, color = name))+
  geom_boxplot()
```


```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = fct_relevel(name, "Waikiki_HA", "CentralPark_NY")
  )
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point

```


## Restructure then plot

```{r}
weather_df %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temp"
  )%>% 
  ggplot(aes(x = temp, fill = observation))+
  geom_density(alpha = .5)+
  facet_grid(~name) +
  theme (legend.position = "bottom")
  viridis::scale_fill_viridis(discrete = TRUE)

```

```{r}

pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(wt_gain = gd18_weight - gd0_weight,
         day_of_tx = as.numeric(day_of_tx))

fas_data = left_join(pup_data, litter_data, by = "litter_number") 

fas_data %>% 
  select(sex, dose, day_of_tx, pd_ears:pd_walk) %>% 
  pivot_longer(
    pd_ears:pd_walk,
    names_to = "outcome", 
    values_to = "pn_day") %>% 
  drop_na(dose, day_of_tx, pn_day) %>% 
  mutate(
    outcome = forcats::fct_reorder(outcome, day_of_tx, median)) %>% 
  ggplot(aes(x = dose, y = pn_day)) + 
  geom_violin() +
  facet_grid(day_of_tx ~ outcome)
```











