---
title: "Data Import"
author: "Olya Besedina"
data: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)


weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

## crate ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
# geom_point creates scatter plot
```

Alternate way to make ggplot

```{r}
weather_df%>%
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

saving initial plots 

```{r}
weather_df %>%  filter(name=="CentralPark_NY")
```

without printing

```{r}
scatterplot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()

scatterplot
```

Adding color

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_point(aes(color = name), alpha = .4)
```

Why do `aes` position matters?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE)
  
#   geom_smooth((se = FALSE)) gives you  smooth line  
# if you put color in geom than it will create color for that particulas plot. 
# if you add color to ggplot aes than all of your plots will be using colors
```

Facet

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(aes(color = name), alpha = .4) +
  geom_smooth(se = FALSE) +
  facet_grid(-name)

# NOT working
```

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(size = 2, se = FALSE)
```

## Some extra stuff
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth(size = 2, se = FALSE)

# not very useful
```

24 density
```{r}
#install.packages("hexbin")
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d()
  
```

## Density plots
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)
  
# density plots look better than histograms
# color in aes colrs the overline 
# fill in aes colors the whole bar
```


```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax))+
  geom_boxplot()

weather_df %>% 
  ggplot(aes(x = name, y = tmax))+
  geom_violin()
```

